from decimal import Decimal
from typing import List, Dict, Any
from datetime import datetime, timezone

NOW_ISO = datetime.now(timezone.utc).isoformat()

CANONICAL_PRODUCTS_GRAPH: List[Dict[str, Any]] = [
    {
        "id": "canon_nike_drifit_legend_black_m",
        "identity_scope": "REAL_WORLD_VERIFIED",
        "brand": "Nike",
        "title": "Nike Men's Dri-FIT Legend Short-Sleeve Training T-Shirt",
        "category": "Apparel",
        "subcategory": "T-Shirts",
        "model": "Dri-FIT Legend Short-Sleeve",
        "style_code": "718833-010",
        "gtin": None,
        "color": "Black",
        "size": "M",
        "variant": "Classic Black",
        "canonical_image_url": "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=600&auto=format&fit=crop&q=80",
        "apex_product_name": "Sports Dry-Fit T-Shirt",
        "apex_price": Decimal("999.00"),
        "apex_mrp": Decimal("1499.00"),
        "verified": True,
        "retailer_offers": [
            {
                "retailer": "nike",
                "store_name": "Nike Official Store",
                "store_domain": "nike.com",
                "store_logo_url": "https://upload.wikimedia.org/wikipedia/commons/a/a6/Logo_NIKE.svg",
                "external_product_id": "718833-010",
                "external_title": "Nike Dri-FIT Legend Men's Training T-Shirt (Black/Matte Silver)",
                "external_product_image": "https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/718833-010/dri-fit-legend-mens-training-t-shirt.png",
                "external_product_url": "https://www.nike.com/in/t/dri-fit-legend-training-t-shirt-1ZtbXq/718833-010",
                "price": Decimal("1095.00"),
                "mrp": Decimal("1095.00"),
                "currency": "INR",
                "brand": "Nike",
                "model": "Dri-FIT Legend",
                "style_code": "718833-010",
                "gtin": None,
                "color": "Black",
                "size": "M",
                "match_type": "VARIANT_EXACT",
                "match_confidence": 1.0,
                "identity_evidence": {
                    "type": "OFFICIAL_MANUFACTURER_SKU",
                    "style_code": "718833-010",
                    "gtin": None,
                    "source": "Nike Direct D2C Style Index",
                    "pdp_verified": True,
                    "image_verified": True,
                    "retrieved_at": NOW_ISO
                },
                "source": "Nike Direct D2C",
                "observed_at": NOW_ISO
            },
            {
                "retailer": "amazon",
                "store_name": "Amazon India",
                "store_domain": "amazon.in",
                "store_logo_url": "https://upload.wikimedia.org/wikipedia/commons/a/a9/Amazon_logo.svg",
                "external_product_id": None,
                "external_title": "Search Nike Dri-FIT Legend on Amazon India",
                "external_product_image": None,
                "external_product_url": "https://www.amazon.in/s?k=Nike+Dri-FIT+Legend+718833-010",
                "price": None,
                "mrp": None,
                "currency": "INR",
                "brand": "Nike",
                "model": "Dri-FIT Legend",
                "style_code": "718833-010",
                "match_type": "SEARCH_FALLBACK",
                "match_confidence": 0.60,
                "identity_evidence": {
                    "type": "SEARCH_FALLBACK",
                    "reason": "Direct active Amazon India ASIN stock not currently verified"
                },
                "source": "Amazon India Search",
                "observed_at": None
            },
            {
                "retailer": "myntra",
                "store_name": "Myntra",
                "store_domain": "myntra.com",
                "store_logo_url": "https://constant.myntassets.com/web/assets/img/icon.5d108c858a0db793700f0be5d3ad1e120e01a500.png",
                "external_product_id": None,
                "external_title": "Search Nike Dri-FIT T-Shirts on Myntra",
                "external_product_image": None,
                "external_product_url": "https://www.myntra.com/nike-dri-fit-tshirt",
                "price": None,
                "mrp": None,
                "currency": "INR",
                "brand": "Nike",
                "model": "Dri-FIT",
                "match_type": "SEARCH_FALLBACK",
                "match_confidence": 0.60,
                "identity_evidence": {
                    "type": "SEARCH_FALLBACK",
                    "reason": "Myntra catalog active style listing unverified"
                },
                "source": "Myntra Search Fallback",
                "observed_at": None
            }
        ]
    },
    {
        "id": "canon_nike_revolution6_black_uk8",
        "identity_scope": "REAL_WORLD_VERIFIED",
        "brand": "Nike",
        "title": "Nike Revolution 6 Next Nature Road Running Shoes",
        "category": "Running",
        "subcategory": "Running Shoes",
        "model": "Revolution 6 Next Nature",
        "style_code": "DC3728-003",
        "gtin": "0195244584285",
        "color": "Black/Iron Grey/White",
        "size": "UK 8",
        "variant": "Black/Iron Grey",
        "canonical_image_url": "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop&q=80",
        "apex_product_name": "Pro Running Shoes",
        "apex_price": Decimal("3499.00"),
        "apex_mrp": Decimal("4499.00"),
        "verified": True,
        "retailer_offers": [
            {
                "retailer": "nike",
                "store_name": "Nike Official Store",
                "store_domain": "nike.com",
                "store_logo_url": "https://upload.wikimedia.org/wikipedia/commons/a/a6/Logo_NIKE.svg",
                "external_product_id": "DC3728-003",
                "external_title": "Nike Revolution 6 Men's Road Running Shoes",
                "external_product_image": "https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/e777ecda-a948-4444-be1f-1eb728b9d81d/revolution-6-road-running-shoes-NCvPsq.png",
                "external_product_url": "https://www.nike.com/in/t/revolution-6-road-running-shoes-NCvPsq/DC3728-003",
                "price": Decimal("3695.00"),
                "mrp": Decimal("3695.00"),
                "currency": "INR",
                "brand": "Nike",
                "model": "Revolution 6",
                "style_code": "DC3728-003",
                "gtin": "0195244584285",
                "color": "Black/Iron Grey",
                "size": "UK 8",
                "match_type": "VARIANT_EXACT",
                "match_confidence": 1.0,
                "identity_evidence": {
                    "type": "OFFICIAL_MANUFACTURER_SKU",
                    "style_code": "DC3728-003",
                    "gtin": "0195244584285",
                    "source": "Nike Direct D2C Style Index",
                    "pdp_verified": True,
                    "image_verified": True,
                    "retrieved_at": NOW_ISO
                },
                "source": "Nike Direct D2C",
                "observed_at": NOW_ISO
            },
            {
                "retailer": "amazon",
                "store_name": "Amazon India",
                "store_domain": "amazon.in",
                "store_logo_url": "https://upload.wikimedia.org/wikipedia/commons/a/a9/Amazon_logo.svg",
                "external_product_id": None,
                "external_title": "Search Nike Revolution 6 on Amazon India",
                "external_product_image": None,
                "external_product_url": "https://www.amazon.in/s?k=Nike+Revolution+6+DC3728-003",
                "price": None,
                "mrp": None,
                "currency": "INR",
                "match_type": "SEARCH_FALLBACK",
                "match_confidence": 0.60,
                "source": "Amazon India Search",
                "observed_at": None
            },
            {
                "retailer": "flipkart",
                "store_name": "Flipkart",
                "store_domain": "flipkart.com",
                "store_logo_url": "https://upload.wikimedia.org/wikipedia/en/thumb/7/7a/Flipkart_logo.svg/330px-Flipkart_logo.svg.png",
                "external_product_id": None,
                "external_title": "Search Nike Revolution 6 on Flipkart",
                "external_product_image": None,
                "external_product_url": "https://www.flipkart.com/search?q=Nike+Revolution+6+DC3728",
                "price": None,
                "mrp": None,
                "currency": "INR",
                "match_type": "SEARCH_FALLBACK",
                "match_confidence": 0.60,
                "source": "Flipkart Search Fallback",
                "observed_at": None
            }
        ]
    },
    {
        "id": "canon_adidas_duramo_speed_black",
        "identity_scope": "REAL_WORLD_VERIFIED",
        "brand": "Adidas",
        "title": "Adidas Men's Duramo Speed Road Running Shoes",
        "category": "Running",
        "subcategory": "Running Shoes",
        "model": "Duramo Speed",
        "style_code": "IE7263",
        "gtin": "4066749964179",
        "color": "Core Black / Cloud White",
        "size": "UK 8",
        "variant": "Core Black",
        "canonical_image_url": "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=600&auto=format&fit=crop&q=80",
        "apex_product_name": "SpeedFlow Marathon Shoes",
        "apex_price": Decimal("2999.00"),
        "apex_mrp": Decimal("3999.00"),
        "verified": True,
        "retailer_offers": [
            {
                "retailer": "adidas",
                "store_name": "Adidas Official Store",
                "store_domain": "adidas.co.in",
                "store_logo_url": "https://upload.wikimedia.org/wikipedia/commons/2/20/Adidas_Logo.svg",
                "external_product_id": "IE7263",
                "external_title": "Adidas Duramo Speed Shoes - Black",
                "external_product_image": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/71a62d04ca03496c8135af8600f72ec6_9366/Duramo_Speed_Shoes_Black_IE7263_01_standard.jpg",
                "external_product_url": "https://www.adidas.co.in/duramo-speed-shoes/IE7263.html",
                "price": Decimal("4599.00"),
                "mrp": Decimal("6599.00"),
                "currency": "INR",
                "brand": "Adidas",
                "model": "Duramo Speed",
                "style_code": "IE7263",
                "gtin": "4066749964179",
                "color": "Core Black",
                "size": "UK 8",
                "match_type": "VARIANT_EXACT",
                "match_confidence": 1.0,
                "identity_evidence": {
                    "type": "OFFICIAL_MANUFACTURER_SKU",
                    "style_code": "IE7263",
                    "gtin": "4066749964179",
                    "source": "Adidas Official Direct Catalog",
                    "pdp_verified": True,
                    "image_verified": True,
                    "retrieved_at": NOW_ISO
                },
                "source": "Adidas Official Direct",
                "observed_at": NOW_ISO
            },
            {
                "retailer": "amazon",
                "store_name": "Amazon India",
                "store_domain": "amazon.in",
                "store_logo_url": "https://upload.wikimedia.org/wikipedia/commons/a/a9/Amazon_logo.svg",
                "external_product_id": None,
                "external_title": "Search Adidas Duramo Speed on Amazon India",
                "external_product_image": None,
                "external_product_url": "https://www.amazon.in/s?k=Adidas+Duramo+Speed+IE7263",
                "price": None,
                "mrp": None,
                "currency": "INR",
                "match_type": "SEARCH_FALLBACK",
                "match_confidence": 0.60,
                "source": "Amazon India Search Fallback",
                "observed_at": None
            }
        ]
    },
    {
        "id": "canon_puma_active_shorts_black",
        "identity_scope": "REAL_WORLD_VERIFIED",
        "brand": "Puma",
        "title": "Puma Men's Active Interlock Gym Training Shorts",
        "category": "Apparel",
        "subcategory": "Shorts",
        "model": "Active Interlock Shorts",
        "style_code": "58672801",
        "gtin": "4063697428416",
        "color": "Puma Black",
        "size": "M",
        "variant": "Puma Black",
        "canonical_image_url": "https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=600&auto=format&fit=crop&q=80",
        "apex_product_name": "Running Shorts",
        "apex_price": Decimal("1299.00"),
        "apex_mrp": Decimal("1799.00"),
        "verified": True,
        "retailer_offers": [
            {
                "retailer": "puma",
                "store_name": "Puma Official Direct",
                "store_domain": "puma.com",
                "store_logo_url": "https://upload.wikimedia.org/wikipedia/en/thumb/d/d4/Puma_complete_logo.svg/330px-Puma_complete_logo.svg.png",
                "external_product_id": "58672801",
                "external_title": "Puma Active Men's Interlock Shorts",
                "external_product_image": "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_750,h_750/global/586728/01/fnd/IND/fmt/png/Active-Men's-Interlock-Shorts",
                "external_product_url": "https://in.puma.com/in/en/pd/active-mens-interlock-shorts/586728",
                "price": Decimal("1199.00"),
                "mrp": Decimal("1499.00"),
                "currency": "INR",
                "brand": "Puma",
                "model": "Active Interlock",
                "style_code": "58672801",
                "gtin": "4063697428416",
                "color": "Puma Black",
                "size": "M",
                "match_type": "VARIANT_EXACT",
                "match_confidence": 1.0,
                "identity_evidence": {
                    "type": "OFFICIAL_MANUFACTURER_SKU",
                    "style_code": "58672801",
                    "gtin": "4063697428416",
                    "source": "Puma Direct D2C Style Index",
                    "pdp_verified": True,
                    "image_verified": True,
                    "retrieved_at": NOW_ISO
                },
                "source": "Puma Direct D2C",
                "observed_at": NOW_ISO
            },
            {
                "retailer": "amazon",
                "store_name": "Amazon India",
                "store_domain": "amazon.in",
                "store_logo_url": "https://upload.wikimedia.org/wikipedia/commons/a/a9/Amazon_logo.svg",
                "external_product_id": None,
                "external_title": "Search Puma Active Shorts on Amazon India",
                "external_product_image": None,
                "external_product_url": "https://www.amazon.in/s?k=Puma+Active+Interlock+Shorts+586728",
                "price": None,
                "mrp": None,
                "currency": "INR",
                "match_type": "SEARCH_FALLBACK",
                "match_confidence": 0.60,
                "source": "Amazon India Search",
                "observed_at": None
            }
        ]
    },
    {
        "id": "canon_milton_thermosteel_flip_750",
        "identity_scope": "APEX_CATALOG_ONLY",
        "brand": "Apex Sports",
        "title": "Insulated Stainless Steel Water Bottle",
        "category": "Accessories",
        "subcategory": "Water Bottles",
        "model": None,
        "style_code": None,
        "gtin": None,
        "color": "Silver",
        "size": "750 ml",
        "variant": "Silver 750ml",
        "canonical_image_url": "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&auto=format&fit=crop&q=80",
        "apex_product_name": "Insulated Stainless Steel Water Bottle",
        "apex_price": Decimal("699.00"),
        "apex_mrp": Decimal("999.00"),
        "verified": False,
        "retailer_offers": []
    }
]
